# Generated by Django 5.2.7 on 2025-10-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuing_organization', models.CharField(max_length=200)),
                ('certification_type', models.CharField(choices=[('course', 'Online Course'), ('certification', 'Professional Certification'), ('award', 'Award'), ('achievement', 'Achievement')], default='certification', max_length=20)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=100)),
                ('credential_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='certifications/')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
    ]
